[project]
name = "nft-example"
authors = []
description = ""
telemetry = false
requirements = [
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait" },
]
[contracts.my-nft]
path = "contracts/my-nft.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2
